version: "3.3"

services:
  backend:
    env_file:
      - ./env_file
    image: gitlab.praktikum-services.ru:5050/std-013-20/sausage-store/sausage-backend:latest
    container_name: sausage-store-backend
    # environment:
    #   # Переменные из application.properties можно заменить переменными окружения
    #   SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
    #   SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    #   # $Env:SPRING_DATASOURCE_USERNAME
    #   SPRING_DATASOURCE_URL: ${PSQL_DATASOURCE}
    #   REPORT_PATH: ./logs
    #   SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    volumes:
      - /home/student/logsBackDocker:/app/logs
    networks:
      - sausage_network
  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-013-20/sausage-store/backend-report:latest
    container_name: sausage-store-backend-report
    environment:
      DB: ${DATA_MONGODB}&tlsCaFile=YandexInternalRootCA.crt
      PORT: 8081
    networks:
      - sausage_network
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-013-20/sausage-store/sausage-frontend:latest
    container_name: sausage-store-frontend
    ports:
      - "80:80"
    networks:
      - sausage_network

networks:
   sausage_network:
    driver: bridge
