version: "3.5"

services:
  backend_blue:
    env_file:
      - ./env_file
    image: gitlab.praktikum-services.ru:5050/std-013-20/sausage-store/sausage-backend:latest
    container_name: blue
    environment:
      - VIRTUAL_HOST=backend
    #   # Переменные из application.properties можно заменить переменными окружения
    #   SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
    #   SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    #   # $Env:SPRING_DATASOURCE_USERNAME
    #   SPRING_DATASOURCE_URL: ${PSQL_DATASOURCE}
    #   REPORT_PATH: ./logs
    #   SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    volumes:
      - /home/student/logsBackDocker:/app/logs
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 30s
      start_period: 20s
      retries: 10 
    networks:
      - sausage_network
  backend_green:
    env_file:
      - ./env_file
    image: gitlab.praktikum-services.ru:5050/std-013-20/sausage-store/sausage-backend:latest
    container_name: green
    environment:
      - VIRTUAL_HOST=backend
    #   # Переменные из application.properties можно заменить переменными окружения
    #   SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
    #   SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    #   # $Env:SPRING_DATASOURCE_USERNAME
    #   SPRING_DATASOURCE_URL: ${PSQL_DATASOURCE}
    #   REPORT_PATH: ./logs
    #   SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    volumes:
      - /home/student/logsBackDocker:/app/logs
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 30s
      start_period: 20s
      retries: 10 
    networks:
      - sausage_network
  backend-report:
    # env_file:
    #   - /home/deployservice/env_file_report
    image: gitlab.praktikum-services.ru:5050/std-013-20/sausage-store/backend-report:latest
    container_name: backend-report
    environment:
      DB: mongodb://std-013-20:P%40ssw0rd@rc1a-xb6q7pmw36t77ryz.mdb.yandexcloud.net:27018/std-013-20?tls=true&tlsCaFile=YandexInternalRootCA.crt
      PORT: 8081
    networks:
      - sausage_network
  # frontend:
  #   image: gitlab.praktikum-services.ru:5050/std-013-20/sausage-store/sausage-frontend:latest
  #   container_name: frontend
  #   ports:
  #     - "80:80"
  #   networks:
  #     - sausage_network

  frontend:
    container_name: nginx
    image: gitlab.praktikum-services.ru:5050/std-013-20/sausage-store/sausage-frontend:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - ./frontend/dist/frontend/:/usr/share/nginx/html
    environment:
      - DEFAULT_HOST=backend
    networks:
      - sausage_network

networks:
   sausage_network:
    driver: bridge
